package lt.vaikri.playground

import org.junit.Assert
import org.junit.Test
import kotlin.math.absoluteValue
import kotlin.math.sign

class Day9 {
    @Test
    fun sample() {
        """
            R 4
            U 4
            L 3
            D 1
            R 4
            D 1
            L 5
            R 2
        """.trimIndent()
            .printAnswers(13, 1)
    }

    @Test
    fun sample2() {
        """
            R 5
            U 8
            L 8
            D 3
            R 17
            D 10
            L 25
            U 20
        """.trimIndent()
            .printAnswers(88, 36)
    }

    @Test
    fun actual() {
        """
            D 2
            R 2
            U 2
            D 2
            L 1
            D 1
            L 1
            D 1
            U 1
            R 2
            U 2
            D 2
            R 2
            D 2
            R 2
            U 2
            D 1
            R 2
            L 2
            R 2
            L 2
            D 2
            R 1
            U 1
            L 2
            D 1
            R 1
            D 2
            U 1
            L 2
            R 1
            U 1
            R 1
            U 1
            L 2
            U 1
            L 2
            R 2
            U 1
            D 2
            R 2
            U 2
            L 1
            R 1
            U 1
            D 1
            U 1
            D 2
            U 1
            R 2
            L 1
            D 1
            U 2
            D 2
            U 1
            R 2
            U 1
            L 2
            R 2
            D 1
            R 1
            U 1
            D 1
            R 1
            U 2
            D 2
            R 2
            D 2
            R 1
            L 2
            D 1
            L 2
            D 2
            U 2
            D 1
            U 1
            L 2
            U 2
            R 2
            D 1
            L 1
            D 2
            L 1
            U 2
            D 2
            R 1
            U 1
            D 2
            R 1
            U 1
            R 2
            L 2
            U 1
            L 2
            R 1
            L 1
            D 2
            R 1
            D 2
            L 1
            R 1
            L 1
            U 2
            R 1
            L 1
            U 2
            D 2
            R 2
            D 1
            L 1
            D 2
            L 3
            R 2
            U 2
            R 1
            U 1
            R 2
            L 2
            D 2
            R 3
            L 2
            R 3
            U 3
            D 3
            U 2
            R 1
            U 3
            D 1
            U 3
            D 1
            U 1
            D 1
            R 1
            L 2
            D 3
            R 2
            U 1
            R 1
            U 2
            D 3
            L 2
            D 2
            R 1
            U 2
            D 1
            R 2
            L 3
            D 2
            L 3
            U 2
            R 2
            U 3
            L 2
            R 1
            U 3
            L 1
            D 2
            R 3
            U 3
            D 3
            R 3
            D 3
            L 3
            D 2
            L 1
            U 1
            R 2
            U 3
            L 2
            R 1
            L 2
            R 3
            L 1
            R 2
            L 1
            D 3
            U 3
            L 1
            R 3
            D 3
            L 2
            U 1
            D 1
            L 3
            D 3
            L 2
            D 1
            U 2
            D 2
            L 1
            U 2
            L 3
            D 1
            U 1
            R 3
            U 2
            L 3
            U 3
            L 2
            R 1
            U 2
            D 1
            R 3
            D 1
            U 1
            L 2
            D 1
            R 3
            D 3
            U 2
            D 3
            U 3
            R 2
            L 2
            R 3
            L 2
            R 2
            D 3
            R 2
            U 1
            D 1
            R 3
            U 3
            L 2
            U 1
            R 3
            U 4
            L 4
            D 4
            U 2
            L 2
            D 3
            L 2
            R 2
            L 4
            U 3
            R 1
            U 2
            R 4
            L 2
            U 3
            R 3
            L 1
            R 1
            U 4
            L 2
            R 1
            U 4
            L 4
            U 1
            D 1
            U 1
            R 2
            L 2
            D 1
            U 3
            D 2
            U 4
            R 4
            L 2
            U 4
            R 4
            D 1
            R 1
            U 2
            L 3
            R 3
            D 2
            L 1
            U 4
            R 3
            D 1
            U 2
            D 3
            R 4
            U 3
            D 3
            R 1
            L 2
            D 4
            L 2
            R 2
            D 4
            U 4
            D 4
            L 4
            U 4
            D 4
            L 2
            R 3
            L 3
            R 3
            L 4
            R 1
            L 1
            U 2
            D 4
            L 4
            R 1
            D 1
            R 3
            L 2
            U 3
            R 4
            U 4
            R 2
            D 4
            R 3
            U 4
            R 4
            L 1
            D 4
            U 3
            R 3
            D 3
            U 3
            R 3
            U 3
            L 3
            D 2
            R 3
            L 1
            R 4
            D 1
            R 3
            D 4
            L 4
            U 4
            R 1
            D 3
            U 4
            R 1
            D 2
            R 4
            D 5
            U 2
            L 2
            U 3
            R 4
            L 2
            U 3
            L 4
            U 3
            D 3
            R 3
            D 3
            L 3
            U 1
            R 3
            L 4
            R 1
            U 3
            R 1
            L 4
            D 5
            U 3
            D 2
            R 2
            U 2
            D 4
            R 4
            U 2
            R 1
            L 3
            D 1
            L 3
            R 4
            L 5
            D 4
            R 2
            L 5
            R 5
            U 1
            D 4
            R 2
            D 5
            R 1
            L 3
            R 1
            U 3
            D 2
            R 1
            L 2
            R 1
            D 5
            U 3
            L 3
            U 4
            L 3
            D 2
            L 4
            U 2
            D 4
            U 2
            L 4
            R 1
            D 1
            U 1
            D 1
            U 2
            L 3
            R 1
            U 1
            L 2
            D 2
            R 3
            L 3
            R 1
            U 4
            R 2
            L 1
            D 2
            R 4
            L 5
            D 1
            R 2
            U 1
            L 2
            U 5
            D 3
            U 3
            D 1
            U 2
            D 4
            U 1
            L 2
            R 4
            L 5
            U 4
            D 3
            U 1
            D 2
            L 5
            U 5
            D 2
            L 2
            D 2
            U 4
            R 5
            D 1
            R 2
            L 2
            D 1
            R 2
            L 6
            U 3
            R 1
            D 6
            U 1
            D 4
            R 6
            U 3
            L 6
            U 3
            L 2
            U 3
            R 4
            U 5
            D 4
            R 5
            D 6
            U 1
            R 2
            U 1
            D 5
            R 4
            L 3
            D 4
            U 5
            L 5
            U 5
            L 4
            U 1
            D 6
            R 6
            L 4
            R 4
            D 1
            R 1
            L 5
            U 2
            D 3
            U 5
            D 6
            R 3
            L 6
            U 6
            D 4
            U 4
            D 3
            L 5
            D 6
            U 5
            R 3
            U 6
            D 4
            U 1
            R 2
            D 1
            L 3
            R 2
            U 5
            R 2
            L 6
            D 3
            R 2
            U 2
            R 5
            U 6
            R 4
            U 4
            D 4
            U 2
            R 6
            U 3
            L 3
            D 1
            R 2
            L 5
            D 5
            U 6
            D 5
            R 1
            D 1
            U 6
            D 4
            R 3
            U 6
            L 5
            U 5
            D 1
            U 6
            L 2
            D 2
            U 6
            L 5
            U 6
            L 2
            D 1
            R 5
            U 4
            R 6
            D 5
            R 1
            L 1
            U 2
            L 1
            R 1
            D 6
            L 6
            R 4
            D 4
            L 3
            D 1
            U 2
            L 3
            R 4
            D 6
            U 5
            D 3
            L 4
            R 6
            L 7
            U 4
            R 4
            L 6
            U 1
            R 4
            L 5
            D 2
            L 2
            D 3
            R 6
            U 6
            R 5
            D 2
            U 5
            L 7
            R 6
            L 3
            U 7
            R 4
            D 7
            R 5
            U 7
            R 6
            U 5
            R 7
            U 4
            D 4
            L 1
            R 2
            D 5
            L 3
            R 6
            D 3
            R 6
            D 4
            U 4
            L 6
            U 5
            D 3
            U 5
            D 5
            R 2
            L 4
            D 1
            L 4
            U 4
            L 4
            D 2
            R 7
            D 2
            L 6
            R 5
            L 7
            U 5
            R 4
            L 2
            R 1
            U 7
            R 6
            D 7
            L 6
            D 2
            L 5
            D 1
            U 6
            L 2
            D 4
            L 6
            D 1
            L 5
            R 6
            D 6
            L 4
            D 4
            R 5
            L 4
            D 2
            U 5
            D 2
            L 7
            R 1
            D 5
            R 3
            L 4
            D 7
            U 2
            R 3
            U 1
            L 1
            U 3
            D 7
            L 7
            D 2
            U 5
            D 2
            U 3
            L 3
            U 5
            L 1
            U 4
            L 1
            D 2
            U 1
            D 7
            R 5
            U 4
            L 2
            D 7
            U 6
            D 3
            U 8
            L 6
            R 1
            U 7
            D 8
            R 5
            D 2
            L 3
            D 7
            U 3
            D 2
            R 4
            L 1
            U 6
            D 4
            R 2
            U 7
            L 6
            U 3
            L 6
            D 3
            L 5
            U 6
            L 2
            R 1
            D 7
            R 7
            L 1
            D 6
            U 2
            R 8
            D 3
            R 1
            U 7
            D 4
            U 8
            R 6
            L 1
            D 4
            U 3
            L 8
            D 1
            R 4
            D 2
            U 8
            D 6
            L 2
            U 6
            R 2
            U 8
            D 4
            R 8
            D 5
            U 4
            D 7
            U 8
            L 2
            U 6
            D 5
            R 5
            D 4
            R 8
            U 5
            R 4
            L 8
            U 7
            R 5
            D 3
            R 7
            L 6
            D 1
            L 5
            U 7
            R 5
            U 4
            R 3
            L 5
            U 1
            R 7
            D 1
            R 8
            U 2
            L 5
            U 5
            R 1
            L 7
            U 2
            D 3
            U 3
            R 8
            U 6
            R 2
            U 1
            R 4
            D 5
            U 5
            R 1
            U 2
            L 1
            R 3
            L 4
            R 4
            D 6
            R 5
            U 3
            D 4
            R 7
            L 7
            D 7
            R 4
            U 5
            R 4
            L 6
            D 1
            R 6
            L 8
            U 7
            L 6
            R 1
            D 2
            U 6
            R 5
            U 8
            D 8
            U 9
            D 3
            R 8
            L 9
            D 7
            R 2
            L 6
            U 8
            R 4
            D 8
            U 8
            L 2
            R 4
            U 1
            D 2
            U 3
            R 8
            L 2
            R 6
            L 4
            U 9
            L 1
            R 1
            D 6
            R 1
            D 2
            R 8
            L 5
            D 8
            U 2
            R 3
            D 7
            L 1
            U 6
            D 4
            U 2
            R 3
            D 5
            U 1
            L 3
            D 5
            U 5
            D 8
            U 4
            L 2
            R 5
            U 7
            R 5
            U 8
            R 6
            L 1
            R 7
            D 3
            R 3
            D 5
            U 1
            R 2
            L 3
            U 8
            R 4
            L 5
            U 7
            D 3
            U 4
            L 9
            U 4
            D 6
            R 9
            L 6
            D 6
            R 6
            U 1
            R 2
            D 2
            U 9
            L 1
            D 6
            U 3
            D 5
            U 7
            R 9
            L 2
            U 8
            L 3
            U 5
            R 8
            D 6
            R 4
            L 8
            R 8
            L 5
            R 7
            U 7
            L 9
            R 4
            U 3
            R 7
            U 2
            L 2
            D 5
            U 10
            D 4
            R 4
            U 6
            L 3
            R 5
            U 7
            D 10
            U 7
            D 8
            L 1
            R 6
            L 3
            U 8
            L 7
            R 5
            L 9
            D 5
            R 3
            L 6
            R 8
            D 4
            L 4
            U 5
            L 7
            R 1
            U 8
            R 3
            D 3
            R 2
            D 3
            U 3
            R 3
            U 6
            R 5
            U 8
            L 7
            U 2
            D 2
            L 3
            D 9
            L 2
            D 3
            R 5
            L 6
            U 1
            L 7
            U 10
            R 2
            L 5
            D 5
            U 1
            L 2
            R 6
            D 8
            U 7
            L 4
            R 6
            U 8
            D 1
            R 5
            D 8
            U 3
            R 1
            D 6
            R 4
            L 10
            D 4
            U 4
            D 4
            R 3
            U 2
            D 1
            R 4
            L 1
            D 4
            L 7
            D 2
            U 7
            D 8
            L 10
            R 7
            L 9
            D 2
            R 4
            D 7
            L 9
            U 9
            R 1
            L 4
            U 1
            D 8
            U 2
            L 7
            R 1
            L 3
            U 3
            D 3
            L 4
            U 10
            L 4
            U 1
            R 4
            D 5
            L 4
            R 5
            D 8
            L 6
            D 1
            U 3
            R 8
            L 7
            D 9
            L 4
            D 4
            U 6
            D 6
            L 4
            R 7
            U 8
            D 10
            U 7
            L 5
            R 2
            L 8
            D 7
            U 8
            L 6
            R 5
            L 7
            R 11
            U 1
            R 4
            D 6
            L 4
            R 5
            L 4
            D 3
            L 7
            R 3
            D 2
            U 10
            R 6
            D 3
            U 4
            R 1
            D 11
            U 3
            D 2
            U 10
            L 7
            U 1
            R 3
            L 1
            R 1
            D 5
            U 3
            L 5
            D 3
            U 8
            L 2
            D 7
            U 5
            L 3
            D 6
            L 6
            D 9
            U 1
            R 11
            U 11
            R 6
            U 1
            R 9
            U 6
            R 6
            D 9
            L 6
            D 8
            U 6
            D 10
            R 10
            D 11
            R 2
            L 10
            D 4
            U 6
            D 6
            R 9
            D 6
            U 7
            L 2
            D 9
            U 10
            D 5
            L 11
            R 4
            U 5
            L 10
            R 5
            U 9
            R 3
            U 6
            L 8
            R 8
            D 6
            L 5
            U 4
            D 8
            L 11
            D 5
            R 8
            U 8
            R 1
            U 3
            R 5
            U 4
            D 8
            R 8
            U 2
            R 2
            U 6
            L 2
            D 1
            R 1
            D 5
            R 11
            U 7
            R 10
            L 4
            U 10
            R 3
            U 1
            D 11
            R 9
            U 6
            L 3
            D 12
            L 7
            D 4
            L 5
            U 7
            D 11
            R 11
            U 1
            R 2
            U 6
            R 7
            L 9
            U 5
            L 7
            D 9
            R 12
            D 12
            R 8
            U 8
            D 6
            R 10
            D 3
            U 1
            D 1
            L 10
            R 4
            D 5
            R 10
            D 3
            U 7
            D 6
            L 9
            R 10
            D 3
            R 9
            L 3
            D 5
            L 5
            R 1
            D 10
            U 11
            R 1
            D 1
            R 11
            D 4
            L 11
            R 6
            L 2
            R 4
            D 4
            R 9
            D 9
            L 3
            U 2
            R 5
            L 1
            R 3
            D 12
            L 9
            D 8
            U 7
            D 2
            R 4
            L 1
            D 9
            U 11
            D 9
            L 6
            D 4
            U 6
            R 8
            D 1
            L 4
            U 8
            D 4
            L 2
            R 1
            L 11
            R 4
            D 5
            L 9
            R 11
            U 1
            D 12
            U 9
            L 8
            R 5
            D 1
            R 9
            L 3
            R 5
            D 3
            U 4
            R 11
            L 4
            R 3
            U 12
            D 1
            U 8
            R 5
            U 10
            L 9
            R 10
            D 4
            L 9
            U 6
            D 4
            U 7
            L 12
            D 7
            R 9
            U 6
            L 4
            D 1
            U 11
            L 3
            D 4
            U 9
            D 10
            U 5
            D 13
            R 9
            D 8
            L 7
            D 11
            U 12
            R 2
            L 12
            R 10
            D 13
            L 6
            U 8
            R 9
            L 7
            R 7
            U 2
            L 5
            R 4
            D 10
            L 4
            D 5
            U 4
            D 13
            R 4
            D 4
            U 9
            R 3
            D 12
            R 2
            U 2
            R 9
            D 10
            U 3
            L 12
            U 9
            L 11
            U 6
            L 3
            U 7
            R 10
            U 13
            L 12
            D 1
            R 6
            D 13
            U 5
            R 2
            L 11
            D 7
            U 1
            D 9
            L 11
            D 6
            R 3
            D 2
            U 5
            L 1
            R 9
            U 7
            D 11
            U 6
            R 2
            U 6
            L 13
            R 4
            L 11
            D 10
            L 1
            U 7
            L 10
            D 1
            U 12
            L 2
            U 5
            D 10
            U 12
            R 13
            U 12
            R 10
            D 13
            R 8
            U 6
            D 11
            L 4
            R 7
            D 6
            L 12
            U 6
            L 8
            R 7
            D 5
            R 7
            D 8
            L 14
            R 10
            U 14
            L 6
            U 14
            R 11
            U 5
            R 1
            L 8
            U 7
            L 3
            D 13
            R 11
            L 14
            U 14
            R 5
            D 9
            R 11
            U 12
            R 13
            L 12
            D 6
            U 7
            L 3
            U 10
            R 13
            D 13
            U 10
            R 12
            D 12
            U 4
            D 12
            U 9
            L 9
            U 13
            D 9
            R 13
            D 13
            R 12
            D 7
            R 4
            L 2
            R 12
            L 8
            U 8
            L 1
            U 4
            R 9
            U 9
            D 13
            R 9
            L 10
            R 12
            D 14
            R 6
            D 9
            L 11
            R 4
            D 6
            R 3
            L 11
            U 9
            R 3
            U 6
            L 2
            D 3
            L 9
            D 9
            R 5
            D 13
            U 14
            R 12
            U 8
            L 12
            D 4
            L 8
            R 13
            D 13
            L 11
            R 6
            U 10
            D 7
            U 12
            R 7
            L 1
            U 2
            R 4
            L 11
            R 6
            L 11
            R 14
            D 7
            R 6
            L 13
            R 8
            D 8
            R 1
            L 3
            R 10
            U 3
            L 5
            U 5
            D 3
            L 4
            D 7
            R 5
            L 6
            U 14
            D 11
            L 13
            R 9
            D 12
            L 2
            D 11
            U 6
            D 14
            R 7
            U 5
            R 5
            U 2
            L 4
            U 12
            D 12
            L 3
            R 6
            L 14
            R 10
            D 13
            U 5
            R 7
            L 6
            U 2
            D 1
            U 5
            R 11
            U 8
            R 2
            L 5
            R 8
            U 5
            R 15
            D 14
            L 7
            R 4
            U 14
            L 13
            U 8
            L 8
            U 4
            D 5
            L 7
            R 9
            U 5
            L 11
            U 3
            R 2
            U 1
            D 13
            L 4
            U 5
            L 13
            R 8
            U 13
            D 15
            L 5
            U 9
            D 1
            L 7
            U 5
            R 9
            L 9
            D 14
            R 7
            U 14
            R 8
            D 1
            R 14
            D 13
            L 15
            D 6
            U 10
            L 10
            R 8
            U 13
            R 12
            U 4
            R 13
            D 2
            R 13
            U 13
            L 6
            D 5
            R 10
            L 5
            R 3
            D 3
            R 15
            D 9
            U 2
            R 7
            U 12
            D 3
            R 8
            D 12
            U 1
            L 13
            D 15
            L 9
            R 15
            U 10
            R 16
            D 5
            R 8
            L 1
            R 7
            D 11
            U 4
            R 10
            L 4
            D 8
            U 8
            D 12
            U 12
            L 7
            U 2
            R 13
            L 14
            D 7
            U 15
            R 2
            D 15
            L 15
            D 10
            U 1
            R 5
            L 9
            R 6
            L 15
            D 6
            U 11
            L 14
            U 10
            R 2
            L 9
            R 4
            U 12
            D 5
            R 7
            U 15
            D 12
            R 1
            U 8
            L 14
            U 8
            D 13
            U 1
            R 3
            U 10
            L 12
            D 9
            L 7
            D 5
            R 7
            D 15
            L 13
            U 2
            D 11
            L 13
            U 14
            L 14
            D 10
            U 9
            L 13
            U 15
            D 5
            U 14
            R 8
            U 8
            R 4
            L 10
            U 13
            R 10
            U 5
            R 12
            D 1
            L 10
            R 11
            D 9
            L 14
            U 15
            D 16
            R 10
            D 14
            U 8
            D 5
            U 7
            D 1
            R 12
            D 10
            L 10
            D 15
            U 8
            L 5
            R 16
            U 13
            R 3
            L 8
            D 11
            L 15
            U 2
            R 12
            L 15
            D 8
            U 14
            L 13
            U 10
            L 14
            R 11
            U 4
            L 1
            R 1
            U 10
            D 8
            U 4
            D 5
            L 8
            R 12
            U 6
            D 16
            L 11
            U 14
            L 5
            D 4
            R 11
            D 5
            R 5
            L 3
            D 5
            R 4
            D 10
            U 13
            L 1
            R 1
            D 5
            R 2
            U 10
            R 12
            L 15
            R 3
            L 13
            U 11
            D 16
            R 6
            D 10
            L 16
            R 9
            U 12
            D 6
            R 16
            U 6
            L 9
            D 10
            L 2
            U 11
            L 5
            D 14
            R 17
            D 9
            R 15
            U 17
            R 12
            L 17
            R 9
            L 14
            R 6
            D 3
            U 12
            D 17
            U 16
            D 7
            U 11
            D 3
            L 5
            U 13
            R 6
            U 16
            D 12
            R 6
            U 1
            L 4
            R 15
            L 13
            D 16
            L 17
            U 1
            D 4
            R 12
            U 1
            L 5
            U 13
            L 12
            U 11
            D 5
            R 15
            L 4
            R 7
            U 6
            D 17
            R 14
            L 16
            D 15
            R 15
            U 7
            R 5
            U 10
            R 5
            L 3
            U 9
            L 6
            U 17
            L 15
            R 14
            D 6
            U 13
            R 11
            L 12
            R 16
            U 4
            D 2
            U 4
            R 17
            D 9
            R 9
            D 7
            R 12
            L 9
            R 16
            D 14
            U 1
            R 12
            U 11
            D 10
            L 10
            D 12
            R 12
            U 7
            D 12
            U 9
            D 15
            R 7
            U 1
            R 4
            U 11
            R 18
            L 6
            D 12
            U 14
            R 12
            D 2
            R 6
            D 9
            L 4
            U 11
            L 13
            D 14
            L 5
            R 13
            L 12
            U 17
            L 11
            R 8
            L 3
            D 6
            U 4
            R 16
            D 14
            U 10
            R 12
            L 7
            R 6
            L 9
            D 13
            U 6
            D 15
            R 17
            L 1
            D 7
            L 6
            R 16
            D 13
            L 5
            R 16
            U 5
            D 2
            R 17
            L 17
            U 18
            L 10
            D 14
            U 9
            D 9
            U 1
            L 8
            R 5
            D 5
            U 12
            D 1
            L 8
            U 13
            R 6
            D 12
            R 6
            D 2
            L 8
            U 11
            L 14
            R 6
            L 17
            D 1
            R 1
            D 3
            U 11
            D 14
            R 8
            U 2
            R 1
            U 17
            L 14
            U 15
            D 17
            L 15
            U 11
            L 7
            D 2
            L 16
            D 7
            L 14
            U 14
            D 5
            R 4
            U 7
            D 4
            R 12
            L 11
            D 4
            U 19
            L 16
            R 13
            L 1
            R 13
            U 12
            R 12
            U 10
            L 7
            R 9
            U 15
            D 3
            R 12
            U 8
            L 5
            R 14
            U 4
            D 2
            L 2
            U 8
            L 6
            D 10
            L 18
            U 4
            D 8
            R 15
            D 11
            R 14
            D 16
            R 14
            D 4
            R 9
            U 14
            L 2
            R 2
            U 16
            R 2
            U 18
            D 6
            R 16
            U 2
            L 7
            U 6
            D 4
            L 9
            U 18
            R 10
            L 17
            R 12
            U 7
            L 10
            U 5
            D 15
            U 6
            L 14
            U 17
            R 11
            U 2
            R 6
            L 5
            D 2
            U 15
            D 6
            U 4
            R 16
            D 7
            L 15
            R 9
            D 6
            R 15
            L 1
            R 2
            L 5
            U 19
            L 6
            U 15
            R 16
            L 12
            D 9
            U 15
            D 7
            L 10
            U 9
            D 15
            L 13
            R 1
            L 17
            R 14
            D 14
            U 19
            D 4
            U 15
            D 1
            R 12
            L 1
            D 14
            U 13
            L 4
            R 15
            L 1
            R 17
            L 9
            D 10
            L 9
            U 2
            L 17
            U 4
            D 7
            R 3
        """.trimIndent()
            .printAnswers(6175, 2578)
    }

    private fun String.printAnswers(single: Int, ten: Int) {
        Assert.assertEquals(single, moveTails(1))
        Assert.assertEquals(ten, moveTails(9))
    }

    private fun String.moveTails(tailCount: Int): Int {
        val positionsOfTail = HashSet<Position>()
        val start = Position(0, 0)
        var head = start
        val tails = Array(tailCount) { start }
        split("\n").forEach {
            val line = it.trim()
            val distance = line.substring(2, line.length).toInt()
            val direction = line[0].direction()
            repeat(distance) {
                head = direction.move(head)
                var follow = head
                tails.update {
                    val updated = follow(follow)
                    follow = updated
                    updated
                }
                positionsOfTail.add(tails.last())
            }
        }
        return positionsOfTail.size
    }

    private inline fun Array<Position>.update(update: Position.() -> Position) {
        for (i in indices) set(i, update(get(i)))
    }

    private fun print(head: Position, tails: Array<Position>, visitedPositions: Set<Position>) {
        visitedPositions.toMutableList().apply {
            add(head)
            addAll(tails)
        }.distinct().sortedBy { it.x }.sortedByDescending { it.y }
            .apply {
                var minX = 0
                var minY = 0
                var maxX = 0
                var maxY = 0
                forEach { (x, y) ->
                    minX = x.coerceAtMost(minX)
                    minY = y.coerceAtMost(minY)
                    maxX = x.coerceAtLeast(maxX)
                    maxY = y.coerceAtLeast(maxY)
                }
                for (y in maxY downTo minY) {
                    for (x in minX..maxX) {
                        val position = Position(x, y)
                        if (position == head) {
                            print('H')
                        } else {
                            val firstIndexOf = tails.indexOfFirst { it == position }
                            if (firstIndexOf != -1) {
                                print(firstIndexOf + 1)
                            } else if (visitedPositions.contains(position)) {
                                print('#')
                            } else {
                                print(Typography.bullet)
                            }
                        }
                    }
                    println()
                }
                println()
            }
    }

    private fun print(head: Position, tail: Position, visitedPositions: Set<Position>) {
        visitedPositions.toMutableList().apply {
            add(head)
            add(tail)
        }.distinct().sortedBy { it.x }.sortedByDescending { it.y }
            .apply {
                var minX = 0
                var minY = 0
                var maxX = 0
                var maxY = 0
                forEach { (x, y) ->
                    minX = x.coerceAtMost(minX)
                    minY = y.coerceAtMost(minY)
                    maxX = x.coerceAtLeast(maxX)
                    maxY = y.coerceAtLeast(maxY)
                }
                for (y in maxY downTo minY) {
                    for (x in minX..maxX) {
                        val position = Position(x, y)
                        if (position == head) {
                            print('H')
                        } else if (position == tail) {
                            print('T')
                        } else if (visitedPositions.contains(position)) {
                            print('#')
                        } else {
                            print(Typography.bullet)
                        }
                    }
                    println()
                }
                println()
            }
    }

    private fun Char.direction(): Direction = when (this) {
        'R' -> Direction.Right
        'U' -> Direction.Top
        'L' -> Direction.Left
        'D' -> Direction.Bottom
        else -> throw RuntimeException("bad direction")
    }

    sealed interface Direction {
        fun move(position: Position): Position

        object Left : Direction {
            override fun move(position: Position): Position = position.moveLeft()
        }

        object Top : Direction {
            override fun move(position: Position): Position = position.moveUp()
        }

        object Right : Direction {
            override fun move(position: Position): Position = position.moveRight()
        }

        object Bottom : Direction {
            override fun move(position: Position): Position = position.moveDown()
        }
    }

    data class Position(val x: Int, val y: Int) {
        fun follow(toFollow: Position): Position = if (shouldFollow(toFollow)) moveTowards(toFollow) else this

        private fun moveTowards(toFollow: Position): Position {
            val difX = toFollow.x - x
            val difY = toFollow.y - y
            var newX = x
            var newY = y
            if (difX.absoluteValue > 0 && difY.absoluteValue > 0) {
                newX += difX.sign
                newY += difY.sign
            } else if (difX.absoluteValue > 1) {
                newX += difX.sign
            } else if (difY.absoluteValue > 1) {
                newY += difY.sign
            }
            return Position(newX, newY)
        }

        private fun shouldFollow(toFollow: Position): Boolean =
            (toFollow.x - x).absoluteValue > 1 || (toFollow.y - y).absoluteValue > 1

        fun position(): String = "$x - $y"

        fun moveRight() = Position(x + 1, y)

        fun moveDown() = Position(x, y - 1)

        fun moveLeft() = Position(x - 1, y)

        fun moveUp() = Position(x, y + 1)
    }
}
